file=open('test.txt','r')
#content=file.read()
#print(content)
#content1=file.readline()
#con=file.readline()
#content2=file.readlines()
#print(content1)
#print(con)
#print(content2)
#file=open('test.txt','w')
#file.write("hello world")
#file.write("good bye")
file=open('test.txt','a')
file.write("appended text")
file.close()