use dataanalytics;
create table products(productid int,productname varchar(20),price int);
insert into products values(1,'bike',20000);
insert into products values(2,'car',2000000);
select * from products;
select min(price) from products;
insert into products values(1,'bike',300000);
insert into products values(2,'car',500000);
select max(price) from products;
select max(price) as largestprice,productid  from products group by productid;
select min(price) as smallestprice,productid from products group by productid;
select avg(price) as avgprice,productid from products group by productid;
select count(*) as numofcolumns  from products;
select sum(price) as tot_price from products group by productid;
select count(productid) from products where price>200000;
insert into products values(1,'cycle',20000);
select count(distinct price) from products;
select sum(price) as tot_price from products group by productname;
select productname,sum(price) as tot_price from products group by productname;
create table customers(customer_id int primary key,name varchar(100));
create table orders(order_id int primary key,customer_id int,product varchar(100),foreign key(customer_id) references customers(customer_id) on delete cascade);
insert into customers values(1,'sai'),(2,'deekshitha');
insert into orders values (101,1,'laptop'),(102,1,'iphone'),(103,2,'tablet');
select * from customers;
select * from orders;
delete from customers where customer_id=1;
select * from customers;
select * from orders;
use data;
select * from emp;
use dataanalytics;
create table employee(id int unsigned,name varchar(30),dept varchar(20),salary int unsigned);
insert into employee values(1,'anusha','cse',30000),(2,'pooja','ece',40000),(3,'sai','cse',35000);
select * from employee;
select salary from employee group by salary;
select * from employee order by salary desc;
select * from employee order by dept asc,salary desc;
select name,salary*12 as annual_sal from employee order by annual_sal desc;
create table orderstable(orderid int,orderdate Datetime,customer_id int,amount decimal(5,2));
insert into orderstable(orderid,orderdate,customer_id,amount) values(101,'2024-09-01',1,250),(102,'2024-09-05',2,300),(103,'2024-09-07',1,150),(104,'2024-09-10',3,450);
select * from orderstable;
select customers.customer_id,customers.name,orderstable.orderid,orderstable.orderdate,orderstable.amount
from customers left join orderstable on customers.customer_id=orderstable.customer_id;
select customers.customer_id,customers.name,orderstable.orderid,orderstable.orderdate,orderstable.amount
from customers inner join orderstable on customers.customer_id=orderstable.customer_id;
select customers.customer_id,customers.name,orderstable.orderid,orderstable.orderdate,orderstable.amount
from customers right join orderstable on customers.customer_id=orderstable.customer_id;
select customers.customer_id,customers.name,orderstable.orderid,orderstable.orderdate,orderstable.amount
from customers  join orderstable on customers.customer_id=orderstable.customer_id;
create table drinks(id int,name varchar(10));
insert into drinks values(1,'sprite'),(2,'pepsi');
create table snacks(id int,name varchar(10));
insert into snacks values(1,'biscuits'),(2,'chips');
select drinks.id,drinks.name,snacks.name from drinks cross join snacks on drinks.id=snacks.id;
create table employees(emp_id int,ename varchar(20),job_desc varchar(25),salary int,hire_date date);
insert into employees values(1,'Ram','admin',100000,date '2024-02-02');
insert into employees values(2,'george','manager',200000,date '2024-02-02');
insert into employees values(3,'Aravind','sales',100000,date,'2024-02-02');
insert into employees values(4,'nivetha','sales',250000,date '2024-02-02');
insert into employees values(5,'Hassain','HR',350000,date '2024-02-02');
select * from employees order by job_Desc;
select job_desc,avg(salary) from employees group by job_desc;
select job_desc,count(emp_id) from employees group by job_Desc;
select job_desc,count(emp_id) from employees where salary>200000 group by job_Desc having count(emp_id)>1;